# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

DEFINES = GL_GLEXT_PROTOTYPES \
          BOOST_HAS_PTHREADS 
CONFIG += debug \
          warn_on \
          qt \
          opengl \
          thread \
          x11 
TEMPLATE = subdirs 
SUBDIRS += wshed \
           main 
