# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./wshed
# Target is a library:  

CONFIG += debug \
          warn_on \
          thread \
          staticlib 
TEMPLATE = lib 
HEADERS += vincent_bild.h \
           vincent_punkt.h \
           vincent_transform.h 
SOURCES += vincent_transform.cpp 
